# Generated by Django 3.0.5 on 2022-03-31 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_producto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
    ]
